WIP 71 node tree builder
codelab-ai/codelab.ai pull request #115
Opened 2020-09-17 18:03 UTC by aburtsev

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #
#71

2020-09-18 07:13 UTC, webberwang requested changes

2020-09-18 07:13 UTC, webberwang commented on apps/web/pages/node/Node-react--type.i.ts
> +// temporary file. Until it'll be not merged in upstream master
Already exists here https://github.com/codelab-ai/codelab.ai/blob/master/libs/shared/interface/node/src/subtypes/react/node-react--enum.ts

2020-09-18 07:13 UTC, webberwang commented on apps/web/pages/node/node.helpers.ts
> +export function generateSelectOption<T>(
Exists here https://github.com/codelab-ai/codelab.ai/blob/master/libs/components/ui/src/components/form/Form.types.ts

2020-09-18 11:43 UTC, aburtsev commented on apps/web/pages/node/Node-react--type.i.ts
> +// temporary file. Until it'll be not merged in upstream master
I'll fix it

2020-09-18 11:45 UTC, aburtsev commented on apps/web/pages/node/node.helpers.ts
> +export function generateSelectOption<T>(
I'll remove it and use the implementation from From.types.ts
Waiting for your decision about #119

2020-09-18 16:55 UTC, webberwang commented on apps/web/pages/node/node.helpers.ts
> +export function generateSelectOption<T>(
Updated

2020-09-20 08:43 UTC, webberwang commented
@aburtsev I refactored the organization a bit. A couple things I noticed.

- Breaking down a component into too many pieces is very difficult to follow. Utilize code folding & we can easily keep all the data required on the same file
- Use lower case naming for function props, as React throws an error
- For mapping data check out `tree-map.spec.tsx`

<img width="1012" alt="ButtonGroup_tsx_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/93707275-c81ab300-fae1-11ea-8347-4ac780e18d49.png">

Hopefully this initial task gives you a better idea of how the project works. I've made some changes how types work will post update in #team on slack.

2020-09-20 11:02 UTC, merged