1235 unit test props pipeline
codelab-ai/codelab.ai pull request #1237
Opened 2021-12-22 12:12 UTC by assimhabeek

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-01-02 13:42 UTC, antonmihaylov requested changes
Great thinking on the hooks solution, seems cleaner.
Also good use of WeakMap
Tests seem good enough, we can always add more when we encounter a bug

Just a couple of comments

2022-01-02 13:42 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/Builder.tsx
> +      parentContext={{
why the name change, parentContext seems a bit confusing, while context follows the react terminology

2022-01-02 13:42 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/hooks/useHookResponse.ts
> +  const getHooksResponse = (
What happens if you add/remove a hook from an element that's not the root?

Does it crash with a React error message? Usually when you execute a different number of hooks each render it does that. Before the solution was to put a unique key related to the number of hooks to the HookWrapper. This causes the Wrapper to re-render every time the number of hooks changes, so technically it's a new element and it doesn't matter if it has a d different number of hooks.

 Now that the executing fn is in the Renderer, and the key depends on the hook count of the root element, I'm wondering if it will cause an issue

2022-01-02 13:42 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/pipes/persistedPropsPipe.ts
> +    const persistedProps = attempt(JSON.parse, element.props.data)
What's the benefit of using attempt vs try-catch?

2022-01-02 13:42 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/renderContainer/RenderContainer.tsx
> +  return (
What's the need for a RenderContainer component, couldn't this functionality be done in the renderFactory, like it was before. It's not much overhead, but it's not readable to have 3 similar components: Renderer, RenderContainer, RenderContainerWithKey

2022-01-02 13:42 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/renderContainer/RenderContainerWithKey.tsx
> +    context.onRendered({ elementId, props: renderedElement.props })
How does this work with a tree deeper than 1 element? As I see, context.onRendered is called only on the root rendered element.

Also, this is similar to the way it was done before, we're essentially bringing back the old pattern of calling onRendered for every rendered element. This caused a massive lag spike each re-render since on every call we are updating the redux state again and again. With 10+ elements it gets very noticeable.

That's why I changed it to update the redux state in 1 batch

2022-01-02 15:21 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/hooks/useHookResponse.ts
> +  const getHooksResponse = (
I didn't change the way we handle that. however I lift the `HookWrapper` As a container. and the container is used to render each element in the tree https://github.com/codelab-ai/codelab.ai/blob/2521ce80c42b161b1bfd1a2a4717e24b86e733fd/libs/frontend/modules/builder/src/renderer/renderContainer/RenderContainer.tsx#L11
The first reason is that now we have access to the props, we also have the ability now to re-render whenever we want by passing `appendToKey`
I tested that while working on MrHost app and it is working fine

2022-01-02 15:37 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/pipes/persistedPropsPipe.ts
> +    const persistedProps = attempt(JSON.parse, element.props.data)
it looks much cleaner, We have one early return then the actually one. 
https://dev.to/coly010/let-s-clean-up-ugly-try-catches-5d4c

2022-01-02 15:42 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/renderContainer/RenderContainer.tsx
> +  return (
`RenderContainerWithKey` is an internal component that shouldn't be used by any other component. The difference is that  `RenderContainer` is called for each element and once it is done rendering it will register its props to Redux. The previous approach of resolving props from the rendered tree was blocked by the HookWrapper.

2022-01-02 15:49 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/renderContainer/RenderContainerWithKey.tsx
> +    context.onRendered({ elementId, props: renderedElement.props })
it does work with deep trees, but I will see how to update state once

2022-01-03 11:00 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/hooks/useHookResponse.ts
> +  const getHooksResponse = (
https://github.com/codelab-ai/codelab.ai/issues/1043
Here's the issue where we removed the wrapper components. Essentially, RenderElement was a react component which acted similarly to how the RenderContainer wraps every element

2022-01-03 11:04 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/pipes/persistedPropsPipe.ts
> +    const persistedProps = attempt(JSON.parse, element.props.data)
I disagree, try-catch is almost universally understandable by any developer, while I had to look up what does attempt do and how does it work. 
But again, it seems like a preference, no issue as long as it works

2022-01-09 08:56 UTC, webberwang requested changes

2022-01-09 08:56 UTC, webberwang commented on libs/frontend/modules/builder/src/renderer/pipes/renderPipeline.tsx
> +)(renderChildrenPipe)
The pipeline should be purely js, no concept of React should be needed. 

We can use use `{renderChildrenPipe()}` inside the tsx view

also use `.ts` extension where possible, such as this file

`renderChildrenPipe`

2022-01-09 09:04 UTC, webberwang requested changes

2022-01-09 09:04 UTC, webberwang commented on libs/frontend/modules/builder/src/renderer/pipes/renderPipeline.tsx
> +export const propsPipeline = compose(
this shouldn't be exported if not used outside this file, same with the others

2022-01-09 09:06 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/pipes/renderPipeline.tsx
> +export const propsPipeline = compose(
we need to export it for tests

2022-01-09 09:06 UTC, webberwang commented on libs/frontend/modules/builder/src/renderer/pipes/renderPipeline.tsx
> +export const propsPipeline = compose(
right nvm

2022-01-09 09:20 UTC, webberwang requested changes
- [ ] Similar to extraElementProps, we do the same for `data-component-id`
- [ ] Also this seems more elegant https://stackoverflow.com/a/44313931/2159920, shared/abstract/types
- [ ] https://github.com/codelab-ai/codelab.ai/blob/c926f8836d07d6d9d94e8862c22fdb8a53003a16/libs/frontend/modules/builder/src/renderer/pipes/propMapBindingsPipe.ts#L14 use PropData interface do ctrl find for `Record<string, any>` and see if they could be substituted
- [ ] Use constant 
![image](https://user-images.githubusercontent.com/26264925/148677686-ac6febe8-3417-4dd0-9e25-55b5dff2daea.png)

2022-01-09 09:20 UTC, webberwang commented on libs/shared/utils/src/props/mergeProps.ts
> +      aggregate[key] = valueA || valueB
could we use https://github.com/jonschlinkert/merge-deep or some lib to achieve the recursive merging?

2022-01-09 09:20 UTC, webberwang commented on libs/frontend/modules/builder/src/renderer/pipes/extraElementPropsPipe.ts
> +    const propsPath = `extraElementProps.${element.id}`
constant would be better here, refactor to `const EXTRA_ELEMENT_PROPS_PREFIX = 'EXTRA_ELEMENT_PROPS_PREFIX_'` and do control search on entire project

perhaps put in `frontend/abstract/core` for now

2022-01-09 09:35 UTC, assimhabeek commented on libs/shared/utils/src/props/mergeProps.ts
> +      aggregate[key] = valueA || valueB
yes, any lib will do the trick. I remember it used to be merge-deep. but since we used Lodash a lot so I chose to use `_.merge` which does the same.

2022-01-09 10:13 UTC, merged