1242 unit test render pipeline utils
codelab-ai/codelab.ai pull request #1243
Opened 2021-12-30 09:05 UTC by assimhabeek

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #1242

2022-01-02 11:03 UTC, webberwang commented
[ ] Refactor Entity interface
- Control search all `id: string` type and replace with `Entity` interface. 
- Put under `libs/shared/abstract/types/src/entity.ts`

[ ] Refactor DgraphEntity interface
- Control search all `uid: string` type and replace with `DgraphEntity` interface
- Put under `libs/shared/abstract/types/src/entity.ts`

2022-01-02 11:04 UTC, webberwang requested changes
[ ] Refactor Entity interface
- Control search all `id: string` type and replace with `Entity` interface. 
- Put under `libs/shared/abstract/types/src/entity.ts`

[ ] Refactor DgraphEntity interface
- Control search all `uid: string` type and replace with `DgraphEntity` interface
- Put under `libs/shared/abstract/types/src/entity.ts`

2022-01-02 14:03 UTC, antonmihaylov requested changes

2022-01-02 14:03 UTC, antonmihaylov commented on libs/shared/utils/src/props/mergeProps.ts
> +    classList.push(srcValue)
What's the need to split the className?

2022-01-02 20:10 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/utils/applyBinding.ts
> +    return merge(targetProps, value)
well `isObjectLike` is shorter than `typeof value === 'object'` and also it check value isn't null.
I am not sure If we really need it but `merge` is safer since it does a deep merge while spread don't.

2022-01-02 20:13 UTC, assimhabeek commented on libs/shared/utils/src/props/mergeProps.ts
> +    classList.push(srcValue)
when writing tests I see ` class1 class2` the random spaces at the beginning and the end  causes problem. we want well spaced className to test easily

2022-01-03 10:43 UTC, antonmihaylov commented on libs/frontend/modules/builder/src/renderer/utils/applyBinding.ts
> +    return merge(targetProps, value)
Spreading null or undefined does nothing. Also, my point was - do we need to merge nested values, or shouldn't we override them?
For example - if we have default props: `{data: [{name: 'asd', someOptionalValue: `asd`}]}`, then we apply a binding that results in `{data: [{name: 'otherName'}]}`, we will still have the `someOptionalValue` in the final result, which is not desirable.

2022-01-03 10:46 UTC, antonmihaylov commented on libs/shared/utils/src/props/mergeProps.ts
> +    classList.push(srcValue)
isn't it easier to .trim it?

2022-01-03 11:44 UTC, assimhabeek commented on libs/frontend/modules/builder/src/renderer/utils/applyBinding.ts
> +    return merge(targetProps, value)
Fixed. thanks for the catch

2022-01-03 11:49 UTC, assimhabeek commented on libs/shared/utils/src/props/mergeProps.ts
> +    classList.push(srcValue)
Restored, 
I was comparing objects, I had to add the space manually for the test to pass 
```    const merged = {
      prop02: {
        nested: 'propB02',
      },
      propB01: 'propB01',
      propA01: 'propA01',
      className: ' classA classB',
    }

2022-01-07 08:46 UTC, webberwang requested changes
Testing

2022-01-07 09:03 UTC, webberwang approved these changes

2022-01-10 01:45 UTC, merged