feat(apps-web): preview for nodes, tree view
codelab-ai/codelab.ai pull request #147
Opened 2020-10-01 12:02 UTC by aburtsev

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2020-10-01 21:01 UTC, webberwang requested changes
A general pattern I noticed is using conditional statements when not required

2020-10-02 18:13 UTC, aburtsev reviewed
I've fixed some of your remarks, but somewhere just left a comment. Please have a look. (I've rebased all commit into one 'code-review' for your convenience but merged into this commit fixes after merging master. So there will be as fixes for code review  as well as fixes after merge master)

2020-10-02 22:40 UTC, webberwang commented on apps/web/pages/node.tsx
> +  const [rootNode, setRootNode] = React.useState<NodeEntity | null>(null)
Entry point can be any node, since they are all connected

2020-10-07 14:25 UTC, webberwang commented
@aburtsev hey, could you clone master and move your old unmerged module to pages/tree instead.
 
I think it’s better to keep them separate for now

2020-10-09 20:37 UTC, webberwang commented
Would this be closed by https://github.com/codelab-ai/codelab.ai/pull/165?

2020-10-09 20:40 UTC, closed without merging

2020-10-09 20:55 UTC, aburtsev commented
> Would this be closed by #165?

Yes. I've moved all changes into the "tree" page