feat(libs-core-renderer): #142 enable form hooks
codelab-ai/codelab.ai pull request #168
Opened 2020-10-12 19:37 UTC by aburtsev

ISSUES CLOSED: #142

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2020-10-13 00:23 UTC, webberwang commented
<img width="1080" alt="Storybook_and_Franz" src="https://user-images.githubusercontent.com/26264925/95801556-824fa580-0caf-11eb-986d-37d603983c02.png">

The `form` isn't getting passed, can you add a spec for reset?

2020-10-13 00:25 UTC, webberwang requested changes
<img width="1080" alt="Storybook_and_Franz" src="https://user-images.githubusercontent.com/26264925/95801556-824fa580-0caf-11eb-986d-37d603983c02.png">

The `form` isn't getting passed, can you add a spec for reset?

The docs show `form` should be added like this `<Form form={form} />`, but `form` isn't available

2020-10-13 00:26 UTC, webberwang requested changes

2020-10-13 00:26 UTC, webberwang commented on libs/core/renderer/src/libs/renderer-components.tsx
> +      if (node.type === 'React.Form') {
<img width="1080" alt="Storybook_and_Franz" src="https://user-images.githubusercontent.com/26264925/95801556-824fa580-0caf-11eb-986d-37d603983c02.png">

The `form` isn't getting passed, can you add a spec for reset?

The docs show `form` should be added like this `<Form form={form} />`, but `form` isn't available

2020-10-13 19:03 UTC, aburtsev commented on libs/core/renderer/src/libs/renderer-components.tsx
> +      if (node.type === 'React.Form') {
It is a bug. To avoid an error message I moved the initiating of form inside Component function and maybe some cache hasn't updated, so when I checked it worked, but I checked today and it isn't worked. I moved it back and everything is fine, but it appeared that this solution works fine in the storybook example, but produces errors on the node-page. I try to find the root of the issue

2020-10-14 02:15 UTC, webberwang requested changes

2020-10-14 02:15 UTC, webberwang commented on apps/web/src/node/ModalForm.tsx
> +              value: 'return this.handlesubmit',
If we're using this approach could we add the hook here without having an extra wrapper component?

2020-10-14 18:58 UTC, aburtsev commented on apps/web/src/node/ModalForm.tsx
> +              value: 'return this.handlesubmit',
When we 'eval' our props we use as context the ctx with libs(React, etc) and renderedProps passed from the parent, hence if we will not use wrapper we can't use formHooks on the level of React.Form (we could use only in descendants), but it's might be very useful (even more we already use it like this on the node-page)

2020-10-14 22:32 UTC, webberwang commented on apps/web/src/node/ModalForm.tsx
> +              value: 'return this.handlesubmit',
is useForm required on level of Form? could be use pass product of useForm from ctx with libs along with antd Form

2020-10-15 20:24 UTC, webberwang requested changes

2020-10-15 20:24 UTC, webberwang commented on libs/core/renderer/src/libs/element-factory.tsx
> +    case 'React.FormHooksWrapper':
We don't have to add this, we can just use a `React.Fragment` to pass down `form`

2020-10-15 20:24 UTC, webberwang commented on libs/core/renderer/src/libs/renderer-components.tsx
> +    if (node.type === 'React.FormHooksWrapper') {
We can just use a `React.Fragment` with an eval prop to pass form down

2020-10-15 20:25 UTC, webberwang commented on apps/web/src/node/ModalForm.tsx
> +              value: 'return this.handlesubmit',
We can create a regular React Fragment and pass down with eval props

2020-10-16 18:34 UTC, aburtsev commented on apps/web/src/node/ModalForm.tsx
> +              value: 'return this.handlesubmit',
Sorry. Maybe I don't get the goal right.
I thought that we want to be able to have form hooks on the level of JSON. I mean we have JSON-config and have our engine which processes this JSON to create the app.
So we have the following options right now:
1. The same as we have right now. But using such an approach we are polluting global ctx
![image](https://user-images.githubusercontent.com/3891411/96294571-3e350b80-0ff5-11eb-8711-55a3a9c11e65.png)
2. Create a wrapper (my current solution)

I still can't get your idea about React.Fragment. To pass down eval props I need to process them on the level of processing JSON. So I need somehow identify that this current context should be extended with form. I can't eval props with form without polluting the global context.

Or you mean that we can pass form as root props?
![image](https://user-images.githubusercontent.com/3891411/96295870-0929b880-0ff7-11eb-911a-eadf5ebda529.png)
But in this case, our JSON would be relying on where we use it and will not be independent and declarative

2020-11-02 06:31 UTC, webberwang commented
closed since we don't need a custom component for hook

2020-11-02 06:31 UTC, closed without merging