321 add unit test
codelab-ai/codelab.ai pull request #328
Opened 2020-11-19 21:38 UTC by artonio

## Current Behavior

## Expected Behavior

Resolves #321

## Related Issue(s)

Fixes #

2020-11-19 23:38 UTC, webberwang requested changes

2020-11-19 23:38 UTC, webberwang commented on apps/api/graph/src/models/user/user.entity.spec.ts
> +    const u = new UserEntity()
what do you think about switching to repository.create({}) for all entity, in let userRepository then in beforeAll assign

2020-11-19 23:38 UTC, webberwang commented on apps/api/graph/src/models/user/user.service.spec.ts
> +    const module = await Test.createTestingModule({
could we extract to `libs/api/providers/config/src/test/config-typeorm.service.ts`, and load using config service

2020-11-19 23:42 UTC, artonio commented on apps/api/graph/src/models/user/user.entity.spec.ts
> +    const u = new UserEntity()
i see what you mean, makes sense, will do

2020-11-20 10:54 UTC, webberwang approved these changes

2020-11-20 18:10 UTC, merged