411 use case generator
codelab-ai/codelab.ai pull request #413
Opened 2020-12-27 03:19 UTC by artonio

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #411

2020-12-28 09:31 UTC, webberwang requested changes

2020-12-28 09:31 UTC, webberwang commented on libs/tools/plugins/codelab/src/schematics/library/use-case/helpers/modify-files.ts
> +const addToClass = (
would this method help? https://github.com/nrwl/nx/blob/9923ce93d57c25624002d428348561e2568ad8ae/packages/workspace/src/utils/ast-utils.ts#L250-L267

2020-12-28 09:31 UTC, webberwang commented on libs/tools/plugins/codelab/src/schematics/library/use-case/helpers/modify-files.ts
> +const insertIntoModule = (host: Tree, options: NormalizedSchema): void => {
the nestjs schematics has to insert import to module as well, we could take some inspiration from that?

https://github.com/nestjs/schematics/blob/6e6855386742bf7c886cd129c4886f720bc63258/src/lib/provider/provider.factory.ts#L75-L95

Or is our use case more complicated because it's separated out to an array variable?

2020-12-29 04:02 UTC, artonio commented on libs/tools/plugins/codelab/src/schematics/library/use-case/helpers/modify-files.ts
> +const insertIntoModule = (host: Tree, options: NormalizedSchema): void => {
exactly, we have a custom array that needs to be modified. actually angular schematics library is using the same method to insert code into arrays inside the module. I do the same thing, I lookup the position to insert code in by using TypeScript Compiler API, (the same API that is used by linters) and InsertChange which return Array<Change> just like addMethod function

2020-12-29 04:03 UTC, artonio commented on libs/tools/plugins/codelab/src/schematics/library/use-case/helpers/modify-files.ts
> +const addToClass = (
no, because we are not inserting a method here

2021-01-02 05:08 UTC, merged