414 front end auth second
codelab-ai/codelab.ai pull request #444
Opened 2021-01-07 05:28 UTC by antonmihaylov

## Current Behavior

## Expected Behavior

## Related Issue

Fixes #414

2021-01-08 03:43 UTC, webberwang commented
- [ ] Refactor to https://github.com/codelab-ai/codelab.ai/blob/master/documentation/getting-started/3-project-architecture.md#input-vs-request

`nx build tools-generators-graphql` will generate the types

- [ ] Add a 1 second delay to each request, this way we can test out our UI's
- [ ] After submit, the the button should be disabled loading state
- [ ] On success the button state will revert as the modal closes
- [ ] Then either a success or error notification will appear

2021-01-08 03:56 UTC, webberwang requested changes

2021-01-08 03:56 UTC, webberwang commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserForm.tsx
> +  hasSubmitButton,
we always show submitButton, but change to disabled loading state

2021-01-08 03:56 UTC, webberwang commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserForm.tsx
> +  const [formData, setFormData] = useState<RegisterUserRequest>({
is there a reason we need this useState?

2021-01-08 03:56 UTC, webberwang commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserModal.tsx
> +  const error =
![image](https://user-images.githubusercontent.com/26264925/103972628-31badd80-5122-11eb-957b-a12b5e24c86d.png)

2021-01-08 06:16 UTC, antonmihaylov commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserForm.tsx
> +  const [formData, setFormData] = useState<RegisterUserRequest>({
Yes, without the state the form input values get reset on each render. https://github.com/rjsf-team/react-jsonschema-form/issues/391

2021-01-08 06:19 UTC, antonmihaylov commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserModal.tsx
> +  const error =
That would mean we will handle errors globally, not in the form components, right?

2021-01-08 13:28 UTC, antonmihaylov commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserForm.tsx
> +  hasSubmitButton,
We don't actually, I'm hiding it here, so that the modal "OK" button acts as a submit button

2021-01-09 08:02 UTC, webberwang commented on libs/modules/user-stories/src/useCases/registerUser/RegisterUserModal.tsx
> +  const error =
yeah that's right

2021-01-09 09:03 UTC, merged