476 nextjs page auth guard
codelab-ai/codelab.ai pull request #499
Opened 2021-01-21 11:54 UTC by antonmihaylov

Fixes #476

2021-01-21 12:23 UTC, webberwang requested changes

2021-01-21 12:23 UTC, webberwang commented on libs/frontend/src/model/store/apollo/apolloClient.tsx
> +  token?: string | undefined,
we can attach header to ctx, I think ctx.req.headers? not sure exactly the shape, but we should remove `any` and type it.

2021-01-21 12:23 UTC, webberwang commented on libs/frontend/src/model/store/apollo/apolloClient.tsx
> +    link: getCombinedLink(token),
forward the header to apollo client instead

![image](https://user-images.githubusercontent.com/26264925/105350393-f13a7580-5b9f-11eb-8090-cd3b7d546191.png)

2021-01-21 12:23 UTC, webberwang commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +      return await ssrGetMe.getServerPage({}, undefined, token)
we shouldn't need to pass token here if headers is forwarded to apolloClient

2021-01-21 12:41 UTC, webberwang requested changes

2021-01-21 12:41 UTC, webberwang commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +export const withAuthGuardServerSideProps = (redirectTo = '/') => {
I think passing callback is better

2021-01-21 12:49 UTC, webberwang requested changes

2021-01-21 12:49 UTC, webberwang commented on apps/web/src/apollo/apollo-page.generated.tsx
> +  token?: string,
this function can't be edited as its generated

2021-01-21 12:55 UTC, webberwang requested changes

2021-01-21 12:55 UTC, webberwang commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +  const cookie = context.req?.headers?.cookie
better to pass context around, defer de-structure to the function that needs the cookie

2021-01-21 12:55 UTC, webberwang commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +    return mergeDeep(result, originalData)
can't use `...` merge?

2021-01-21 19:56 UTC, antonmihaylov commented on libs/frontend/src/infrastructure/auth/authTokenStorage.ts
> +  if (isServer) return null
We do, js-cookie is just a wrapper around client-side cookies. It uses ```document.cookie``` under the hood. If we're on the server, there is no document

2021-01-21 20:04 UTC, antonmihaylov commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +      return await ssrGetMe.getServerPage({}, undefined, token)
If the request fails, e.g. if the user is not authenticated it throws an error and doesn't display the page at all.

2021-01-21 20:05 UTC, antonmihaylov commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +    return mergeDeep(result, originalData)
Nope, it's nested. The ```data``` object won't get merged if we use ```...```

2021-01-21 20:31 UTC, antonmihaylov commented on libs/frontend/src/infrastructure/auth/withAuthServerSideProps.ts
> +export const withAuthGuardServerSideProps = (redirectTo = '/') => {
I made this more so that we have an example. We can be flexible with ```withAuthServerSideProps```, where you get the user as a callback param

2021-01-23 10:00 UTC, webberwang commented on libs/frontend/src/infrastructure/auth/authTokenStorage.ts
> +  if (isServer) return null
would this package help? https://github.com/reactivestack/cookies/tree/master/packages/react-cookie/#readme

2021-01-23 10:03 UTC, antonmihaylov commented on libs/frontend/src/infrastructure/auth/authTokenStorage.ts
> +  if (isServer) return null
Not much. It's for using cookies in a component as far as i see. And it probably is still a wrapper around document.cookie

2021-01-23 10:07 UTC, webberwang commented on libs/frontend/src/model/store/apollo/apolloClient.tsx
> +export interface ApolloContext {
is there a context type from apollo?

2021-01-23 10:07 UTC, webberwang commented on libs/frontend/src/model/store/apollo/apolloClient.tsx
> +    ssrMode: isServer, // Disables forceFetch on the server (so queries are only run once)
wouldn't we want to fetch on server so we can redirect serverside?

2021-01-23 11:05 UTC, antonmihaylov commented on libs/frontend/src/model/store/apollo/apolloClient.tsx
> +export interface ApolloContext {
Not sure. But I don't know think it would make sense. We can add anything to the context with a setContext link, like in authLink

2021-01-23 11:05 UTC, antonmihaylov commented on libs/frontend/src/model/store/apollo/apolloClient.tsx
> +    ssrMode: isServer, // Disables forceFetch on the server (so queries are only run once)
Got thay from Apollo docs https://www.apollographql.com/docs/react/performance/server-side-rendering/

There are some benefits to ssrMode which we can use later on perhaps

2021-01-23 11:12 UTC, merged