include ebs deploy in cicd (#700)
codelab-ai/codelab.ai pull request #701
Opened 2021-03-29 21:43 UTC by svitalii33

* update cicd config

* aws config profile

* setting eb-cli config

* simplify eb setup

* update branches to run deploy

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2021-03-30 04:18 UTC, webberwang requested changes

2021-03-30 04:18 UTC, webberwang commented on .platform/hooks/prebuild/yarn.sh
> +sudo curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -
could we remove this, and move to circleci ci. we wouldn't want this to trigger locally

2021-03-30 04:18 UTC, webberwang commented on package.json
> -    "node": ">=13",
we'd still want this requirement, could we make it work on aws

2021-03-30 04:28 UTC, webberwang requested changes

2021-03-30 04:28 UTC, webberwang commented on .ebignore
> +/node_modules
I think better to ignore all, then re-add required folders

2021-03-30 04:28 UTC, webberwang commented on .circleci/config.yml
> +            echo "aws_access_key_id=$AWS_ACCESS_KEY" >> ~/.aws/config
we would use vault

2021-03-30 04:28 UTC, webberwang commented on .circleci/config.yml
> +  python:
is this being used?

2021-03-30 07:08 UTC, svitalii33 commented on .platform/hooks/prebuild/yarn.sh
> +sudo curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -
It is required step to run yarn command in beanstalk

2021-04-01 04:16 UTC, webberwang requested changes

2021-04-01 04:16 UTC, webberwang commented on .platform/hooks/prebuild/yarn.sh
> +sudo curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -
Can this file be removed now that we have correct node version?

2021-04-01 04:16 UTC, webberwang commented on .circleci/config.yml
> +      - run:
We have a job for this right?

2021-04-01 08:13 UTC, svitalii33 commented on .platform/hooks/prebuild/yarn.sh
> +sudo curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -
As I mentioned in the comment, above command is required to install yarn in prebuild stage.

2021-04-01 15:35 UTC, webberwang requested changes

2021-04-01 15:35 UTC, webberwang commented on .platform/hooks/prebuild/yarn.sh
> +yarn install --frozen-lockfile --prod=true
is this required?

2021-04-01 15:36 UTC, webberwang requested changes

2021-04-01 15:36 UTC, webberwang commented on .circleci/config.yml
> +            eb use app-staging --region ap-east-1 --profile eb-cli
We have `AWS_REGION`

2021-04-01 19:02 UTC, merged